# stages:
#   - deploy

# variables:
#   DEPLOY_USER: "root"

# .before_script_template: &before_script_def
#   before_script:
#     - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh

# # Server API 1
# deploy_server_api_1:
#   stage: deploy
#   variables:
#     SERVER_IP: "1.201.18.142"
#     SERVER_PORT: "27400"
#   <<: *before_script_def
#   only:
#     - main
#   before_script:
#     - *before_script_def
#     - ssh-keyscan -p $SERVER_PORT $SERVER_IP >> ~/.ssh/known_hosts
#   script:
#     - |
#       ssh -p $SERVER_PORT $DEPLOY_USER@$SERVER_IP "
#         cd /var/www/2025_ai_toktak_be && \
#         git pull origin main && \
#         service toktak restart && \
#         service toktak-tasks restart
#       "

# # Server SNS 1
# deploy_server_sns_1:
#   stage: deploy
#   variables:
#     SERVER_IP: "1.201.18.231"
#     SERVER_PORT: "22"
#   <<: *before_script_def
#   only:
#     - main
#   before_script:
#     - *before_script_def
#     - ssh-keyscan -p $SERVER_PORT $SERVER_IP >> ~/.ssh/known_hosts
#   script:
#     - |
#       ssh -p $SERVER_PORT $DEPLOY_USER@$SERVER_IP "
#         cd /var/www/2025_ai_toktak_be && \
#         git pull origin main && \
#         service consumer-facebook restart && \
#         service consumer-tiktok restart && \
#         service consumer-twitter restart && \
#         service consumer-youtube restart && \
#         service consumer-thread restart && \
#         service consumer-instagram restart
#       "

# # Server Toktak 1
# deploy_server_toktak_1:
#   stage: deploy
#   variables:
#     SERVER_IP: "103.9.159.82"
#     SERVER_PORT: "222"
#   <<: *before_script_def
#   only:
#     - main
#   before_script:
#     - *before_script_def
#     - ssh-keyscan -p $SERVER_PORT $SERVER_IP >> ~/.ssh/known_hosts
#   script:
#     - |
#       ssh -p $SERVER_PORT $DEPLOY_USER@$SERVER_IP "
#         cd /var/www/toktak && \
#         git pull origin main && \
#         service toktak restart && \
#         service toktak-tasks restart && \
#         service consumer_toktak restart && \
#         service consumer_toktak_tiktok restart && \
#         service consumer_toktak_twitter restart && \
#         service consumer_toktak_youtube restart && \
#         service consumer_toktak_thread restart && \
#         service consumer_toktak_instagram restart
#       "
