version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  sns-consumers:
    build:
      context: .
      dockerfile: Dockerfile.sns
    env_file:
      - .env
    depends_on:
      - redis
      - api
    networks:
      - app-network

  content-creator:
    build:
      context: .
      dockerfile: Dockerfile.content
    env_file:
      - .env
    depends_on:
      - redis
      - api
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
