from enum import Enum


class LimitSNS(Enum):
    """Enum for SNS limits."""

    WAIT_SECOND_CHECK_STATUS = 30
    WAIT_PER_API_CALL = 2

    FACEBOOK_PER_HOUR = 200
    INSTAGRAM_PER_HOUR = 200
    THREAD_PER_HOUR = 200
    TWITTER_PER_HOUR = 3600
    TIKTOK_PER_HOUR = 200
    YOUTUBE_PER_HOUR = 200

    FACEBOOK_LIMIT_POST_PER_HOUR = 4
    INSTAGRAM_LIMIT_POST_PER_HOUR = 4
    THREAD_LIMIT_POST_PER_HOUR = 4
    TWITTER_LIMIT_POST_PER_HOUR = 0
    TIKTOK_LIMIT_POST_PER_HOUR = 20
    YOUTUBE_LIMIT_POST_PER_HOUR = 10

    FACEBOOK_LIMIT_POST_PER_DAY = 0
    INSTAGRAM_LIMIT_POST_PER_DAY = 25
    THREAD_LIMIT_POST_PER_DAY = 0
    TWITTER_LIMIT_POST_PER_DAY = 0
    TIKTOK_LIMIT_POST_PER_DAY = 20
    YOUTUBE_LIMIT_POST_PER_DAY = 10
